### ISSUE TITLE
Please tell me how to fix this error

### ISSUE THREAD

**Issue by Fight4fun-ych** [LeapLabTHU/DAT-Detection#3]
Now i have the new questions as follows

2023-11-08 03:17:02,487 - mmdet - INFO - Set random seed to 67311741, deterministic: False
Traceback (most recent call last):
  File "/home/ych/DAT-Detection/DAT-Detection-main/tools/train.py", line 247, in <module>
    main()
  File "/home/ych/DAT-Detection/DAT-Detection-main/tools/train.py", line 219, in main
    model.init_weights()
  File "/home/ych/.conda/envs/python39/lib/python3.9/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/home/ych/DAT-Detection/DAT-Detection-main/models/backbones/dat.py", line 332, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/ych/DAT-Detection/DAT-Detection-main/models/backbones/loading.py", line 362, in load_checkpoint
    table_current = model.state_dict()[k1]
KeyError: 'backbone.stages.0.attns.1.rpe_table'

when i try "python tools/train.py configs/dat/rtn_tiny_1x_4n_dp00_lr2.py" and i make sure i have update the pretrain variable in `<CONFIG_FILE>` as 
_base_ = [
    '../_base_/models/retinanet_dat_fpn.py',
    '../_base_/datasets/coco_detection.py',
    '../_base_/schedules/schedule_1x.py',
    '../_base_/default_runtime.py'
]

pretrained = '/home/ych/DAT-Detection/DAT-Detection-main/rtn_dat_t_1x.pth'

could somebody help me????

**Comment by Fight4fun-ych** [comment]
I've now successfully installed models by commenting out a portion of the library, but a new issue has arisen，
python tools/test.py configs/_base_/models/retinanet_dat_fpn.py /rtn_dat_t_1x.pth --eval bbox segm
/home/ych/.conda/envs/python39/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ych/DAT-Detection/DAT-Detection-main/tools/test.py", line 285, in <module>
    main()
  File "/home/ych/DAT-Detection/DAT-Detection-main/tools/test.py", line 148, in main
    cfg = compat_cfg(cfg)
  File "/home/ych/.conda/envs/python39/lib/python3.9/site-packages/mmdet/utils/compat_config.py", line 16, in compat_cfg
    cfg = compat_imgs_per_gpu(cfg)
  File "/home/ych/.conda/envs/python39/lib/python3.9/site-packages/mmdet/utils/compat_config.py", line 39, in compat_imgs_per_gpu
    if 'imgs_per_gpu' in cfg.data:
  File "/home/ych/.conda/envs/python39/lib/python3.9/site-packages/mmcv/utils/config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/ych/.conda/envs/python39/lib/python3.9/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'data'


I haven't changed anything except the dataset path, please why is that？

**Comment by Fight4fun-ych** [comment]
Now I can use “python tools/test.py configs/dat/rtn_tiny_1x_4n_dp00_lr2.py rtn_dat_t_1x.pth --eval bbox”, However, when I run “python tools/train.py configs/dat/rtn_tiny_1x_4n_dp00_lr2.py”, the following problems occur

Traceback (most recent call last):
  File "/home/ych/DAT-Detection/DAT-Detection-main/tools/train.py", line 247, in <module>
    main()
  File "/home/ych/DAT-Detection/DAT-Detection-main/tools/train.py", line 219, in main
    model.init_weights()
  File "/home/ych/.conda/envs/python39/lib/python3.9/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/home/ych/DAT-Detection/DAT-Detection-main/models/backbones/dat.py", line 332, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/ych/DAT-Detection/DAT-Detection-main/models/backbones/loading.py", line 311, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/ych/DAT-Detection/DAT-Detection-main/models/backbones/loading.py", line 287, in _load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/ych/.conda/envs/python39/lib/python3.9/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ych/.conda/envs/python39/lib/python3.9/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'm'.

I made sure I wrote the evaluated model path to configs/dat as pretrain，can you tell me how to solve this problem

**Comment by anzr299** [comment]
I am having the same problem. Any help would be appreciated!!

**Comment by anzr299** [comment]
Did you fix the problem?

**Comment by Fight4fun-ych** [comment]
> I am having the same problem. Any help would be appreciated!!

yes，backbone should use dat_pp_tiny_in1k_224.pth to initialize，download by classfication mission

**Comment by anzr299** [comment]
> > I am having the same problem. Any help would be appreciated!!
> 
> yes，backbone should use dat_pp_tiny_in1k_224.pth to initialize，download by classfication mission

Should I continue using `pretrained` or should I use `load_from`?
Also what do you mean by the classification mission?
